Day16/Open-ITBlog/article/urls.py
from django.urls import path,re_path
from . import views
app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list,name = 'article_list'),
    path('article-detail/<int:id>/',views.article_detail,name = 'article_detail'),
    path('article-create/',views.article_create,name = 'article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name = 'article_update'),
    path('article-own/',views.article_own,name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/',views.searchtag,name = 'searchtag'),
]

Day16/Open-ITBlog/message/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/12/5 16:32
@desc:
'''

from django.urls import path
from . import views
app_name = 'message'

urlpatterns = [
    path('reply/<int:id>/',views.reply,name='reply'),
    path('commit/<int:id>/',views.commit,name='commit'),
    path('message/',views.get_message,name='message'),
    path('message-list/',views.message_list,name='message_list'),
]

Day16/Open-ITBlog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from userprofile import views
from message.views import get_content

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('remark/',include('remark.urls',namespace='remark')),
    path('message/',include('message.urls',namespace='message')),
    path('password-reset/',include('password_reset.urls')),
    path('form/',get_content),
    path('',views.user_login),

]

Day16/Open-ITBlog/remark/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/12/6 16:06
@desc:
'''
from django.urls import path
from . import views
app_name = 'remark'

urlpatterns = [
    path('remark/<int:id>/',views.remark,name='remark'),
    path('reply/<int:id>/<int:aid>',views.reply,name='reply'),
    path('commit/<int:id>/<int:aid>',views.commit,name='commit'),

]

Day16/Open-ITBlog/userprofile/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/11/20 11:34
@desc:
'''
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),

]

Day16/Open-ITBlog/templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/code.css' %}">
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>

</body>
</html>

Day16/Open-ITBlog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">关注"码农架构"微信公众号，一线码农的技术之路经验分享。</p>
    </div>
</footer>

Day16/Open-ITBlog/templates/header.html
<!-- 定义导航栏 -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <!-- 导航栏商标 -->
    <a class="navbar-brand" href="{% url 'article:article_own'%}">我的博客</a>
    <a  class="navbar-brand" href="{% url 'message:message_list'%}">留言板</a>
    <!-- 导航入口 -->
    <div >
      <ul class="navbar-nav">
        <!-- 条目 -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
          <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>

              {% if user.is_authenticated %}
        <!-- 如果用户已经登录，则显示用户名下拉框 -->
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
              <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>
            </div>
        </li>

    <!-- 如果用户未登录，则显示 “登录” -->
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
        </li>
    <!-- if 语句在这里结束 -->
           {% endif %}
          <a href="#" >
              <img src="{% static 'bootstrap/image/timg.jpeg' %}" height="30" width="30">
          </a>
      </ul>
    </div>
  </div>
</nav>

{% if user.is_authenticated %}
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function(index, layero) {
                    location.href='{% url "userprofile:delete" user.id %}'
                },
            })
        }
    </script>
{% endif %}

Day16/Open-ITBlog/templates/message-list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    留言信息
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}" rel="stylesheet" type="text/css" />
<!-- 定义放置文章标题的div容器 -->
<section class="comments">
<article class="comment">
  <!--<div class="comment-body">-->
  <!--</div>-->
</article>
      <div class="box1">
         <p>留言列表: </p>
      </div>
    <div class="box2">
        <a href="/form/"> <p>我要留言:</p></a>
    </div>
  <article class="comment">
   {% for obj in objs %}
  <a class="comment-img" href="#non">
    <img src="" alt="" width="50" height="50">
  </a>
  <div class="comment-body">
      <p class="attribution">&nbsp;<p class="attribution">{{obj.id}}楼 <a href="#non">{{obj.name}}</a></p>
        <div class="text">
            <p>{{ obj.text}}</p>
        </div>

      <p class="attribution">{{ obj.create_time }} &nbsp;<a href="{% url 'message:reply' obj.id%}"> 回复</a></p>

        {% for com in comObjs %}
            {% if obj.id == com.mid %}
            <div class="">
             <span class="box4">{{com.name}}</span>：<span class="">{{com.text}}</span>
             </div>
            <div class="attribution">
                {{ com.create_time }}
            </div>
            <br/>

            {% endif %}
        {% endfor%}


      {% if relay %}
          {% if uid == obj.id %}
            <form method="post" action="{% url 'message:commit' obj.id%}">
                {% csrf_token %}
               <div class="">
                   <input name="text" type="text">
                    <p><button type="submit" class="box3">提交</button></p>
               </div>
            </form>
          {% endif %}

      {% endif %}

        <HR style= " FILTER: progid:DXImageTransform.Microsoft.Glow ( color= #987cb9 ,strength = 10) " width= "100%" color= #987 cb9 SIZE =1>
  </div>
    {% endfor %}
  </article>

</article>
</section>
{% endblock content %}

Day16/Open-ITBlog/templates/msg.html
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    留言板
{% endblock title %}
{% block content %}
<body>
<link href="{% static 'bootstrap/css/style.css' %}" rel="stylesheet" type="text/css" />
<form action="/form/" method="post" class="smart-green">
    <h1>留言信息</h1>
    <label>
        <span>姓名 :</span>
        <input id="name" type="text" name="name" class="error" placeholder="请输入您的姓名"/>
        <div class="error-msg"></div>
    </label>

    <label>
        <span>邮箱 :</span>
        <input id="email" type="email" value="" name="email" placeholder="请输入您的邮箱地址"/>
        <div class="error-msg"></div>
    </label>
    <label>
        <span>内容 :</span>
        <textarea id="message" name="message"  placeholder="请输入您的建议"></textarea>
        <div class="error-msg"></div>
    </label>
    <div class="success-msg"></div>
    <label>
        <span>&nbsp;</span>
        <input type="submit" class="button" value="提交"/>
    </label>
    {#避免提交表单时出现CSRF验证失败. 请求被中断.的403错误#}
    {% csrf_token %}
</form>
</body>

{% endblock content %}