Day16/Open-ITBlog/article/urls.py
from django.urls import path,re_path
from . import views
app_name = 'article'

urlpatterns = [
    path('article-list/',views.article_list,name = 'article_list'),
    path('article-detail/<int:id>/',views.article_detail,name = 'article_detail'),
    path('article-create/',views.article_create,name = 'article_create'),
    path('article-delete/<int:id>/',views.article_delete,name='article_delete'),
    path('article-update/<int:id>/',views.article_update,name = 'article_update'),
    path('article-own/',views.article_own,name='article_own'),
    re_path('searchtag/(?P<category>.{0,20})/',views.searchtag,name = 'searchtag'),
]

Day16/Open-ITBlog/message/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/12/5 16:32
@desc:
'''

from django.urls import path
from . import views
app_name = 'message'

urlpatterns = [
    path('reply/<int:id>/',views.reply,name='reply'),
    path('commit/<int:id>/',views.commit,name='commit'),
    path('message/',views.get_message,name='message'),
    path('message-list/',views.message_list,name='message_list'),
]

Day16/Open-ITBlog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from userprofile import views
from message.views import get_content

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/',include('article.urls',namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('remark/',include('remark.urls',namespace='remark')),
    path('message/',include('message.urls',namespace='message')),
    path('password-reset/',include('password_reset.urls')),
    path('form/',get_content),
    path('',views.user_login),

]

Day16/Open-ITBlog/remark/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/12/6 16:06
@desc:
'''
from django.urls import path
from . import views
app_name = 'remark'

urlpatterns = [
    path('remark/<int:id>/',views.remark,name='remark'),
    path('reply/<int:id>/<int:aid>',views.reply,name='reply'),
    path('commit/<int:id>/<int:aid>',views.commit,name='commit'),

]

Day16/Open-ITBlog/userprofile/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: urls.py
@time: 2018/11/20 11:34
@desc:
'''
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),

]

Day16/Open-ITBlog/article/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone

class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    category = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

Day16/Open-ITBlog/message/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Message(models.Model):
    name = models.CharField(max_length=20,verbose_name='姓名',null=False, blank=True, default="")
    email = models.EmailField(verbose_name='邮箱',null=False,blank=True,default="")
    text = models.TextField(verbose_name='留言内容',null=False,blank=True,default="")
    create_time = models.DateTimeField(default=timezone.now,verbose_name='创建时间',null=False,blank=False)

    class Meta:
        verbose_name = '留言板内容'
        ordering = ['-create_time']
        db_table = "message"


class Commit(models.Model):
    name = models.CharField(max_length=20,verbose_name='回复人姓名',null=False)
    text = models.TextField(verbose_name='回复内容',null=False,blank=True,default="")
    create_time = models.DateTimeField(default=timezone.now,verbose_name='创建时间',null=False,blank=False)
    mid = models.IntegerField(default=0)
    class Meta:
        verbose_name = '回复内容'
        ordering = ['-create_time']
        db_table = "commit"

Day16/Open-ITBlog/article/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-  
'''
@author: xiaoshui
@contact: opsonly.com@gmail.com
@file: forms.py
@time: 2018/11/19 16:39
'''

from django import forms
from .models import ArticlePost
from django.db import models

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body','category')


TOPIC_CHOICES=(
    ('level1','Bad'),
    ('level2','Soso'),
    ('level3','Good'),
)

class RemarkForm(forms.Form):
    subject=forms.CharField(max_length=100,label='Mark Board')
    mail=forms.EmailField(label='email')
    topic=forms.ChoiceField(choices=TOPIC_CHOICES,label='choose one topic')
    message=forms.CharField(label='content for mark',widget=forms.Textarea)
    cc_myself=forms.BooleanField(required=False,label='watch this tie')

class Remark(models.Model):
    subject = models.CharField(max_length=100)
    mail = models.EmailField()
    topic = models.CharField(max_length=100)
    message = models.CharField(max_length=300)
    cc_myself = models.BooleanField()

    def __str__(self):
        return self.subject

    class Meta:
        ordering=['subject']

Day16/Open-ITBlog/article/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import *
# Create your views here.
from .models import *
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.views.generic.edit import FormView
from remark.models import Remark,ArticleReply
import markdown

def article_list(request):
    if request.user.is_authenticated:
        user_id = request.user.id
        #articles = ArticlePost.objects.filter(author_id=user_id)
        articles = ArticlePost.objects.all()
        context = { 'articles':articles }
        return  render(request,'article/list.html',context)
    else:
        articles = ArticlePost.objects.all()
        context = { 'articles':articles }
        return render(request,'article/list.html',context)

#login_required(login_url='/userprofile/login/')
def article_detail(request,id):
    article = ArticlePost.objects.get(id = id)
    remark = Remark.objects.filter(aid=id)
    article.body = markdown.markdown(article.body,
                                     extensions = [
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                     ])

    remark = Remark.objects.all()
    articleReply = ArticleReply.objects.all()
    context = {
        'article': article,
        'remark': remark,
        'articleReply': articleReply,
    }
    return  render(request,'article/detail.html',context)



@login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            print(request.POST)
            new_article = article_post_form.save(commit=False)
            user_id = request.user.id
            new_article.author = User.objects.get(id=user_id)
            new_article.save()
            return redirect("article:article_list")
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        context = { 'article_post_form':article_post_form }
        return render(request,'article/create.html',context)

@login_required(login_url='/userprofile/login/')
def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect("article:article_list")

@login_required(login_url='/userprofile/login/')
def article_update(request,id):
    article = ArticlePost.objects.get(id=id)
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)

        if article_post_form .is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()

            return redirect("article:article_detail",id = id)
        else:
            return HttpResponse("表单内容有误，请重新填写")

    else:
        article_post_form = ArticlePostForm()
        context = {'article':article,'article_post_form':article_post_form}
        return render(request,'article/update.html',context)

def remark(request):
    if request.method == "POST":
        form = RemarkForm(request.POST)
        if form.is_valid():
            myremark = Remark()
            myremark.subject = form.cleaned_data['subject']
            myremark.mail = form.cleaned_data['mail']
            myremark.topic = form.cleaned_data['topic']
            myremark.message = form.cleaned_data['message']
            myremark.cc_myself = form.cleaned_data['cc_myself']
            myremark.save()
    else:
        form = RemarkForm()

    ctx = {
        'form':form,
        'ties':Remark.objects.all()
    }

    return render(request,'article/message.html',)

def article_own(request):
    articles = ArticlePost.objects.filter(author_id=request.user.id)


    # articles.body = markdown.markdown(articles.body,
    #                                  extensions = [
    #                                      'markdown.extensions.extra',
    #                                      'markdown.extensions.codehilite',
    #                                      'markdown.extensions.toc',
    #                                  ])
    context = {'articles': articles}
    return  render(request,'article/own.html',context)


def searchtag(request,category):
    tag = category
    articles = ArticlePost.objects.filter(category=category)

    context = {
        'articles':articles,
    }
    return render(request,'article/tag.html',context)

Day16/Open-ITBlog/message/views.py
from django.shortcuts import render
from .models import Message,Commit
from django.http import HttpResponseRedirect
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse

# Create your views here.
def get_message(request):
    return render(request,'msg.html')

def get_content(request):
    if request.method == 'POST':
        if request.POST['name'] == '' and  request.POST['message'] == '':
            return HttpResponse("<h2>表单填写有误</h2>")
        else:
            name = request.POST.get('name','')
            email = request.POST.get('email','')
            message = request.POST.get('message','')

            Q_message = Message()
            Q_message.name = name
            Q_message.email = email
            Q_message.text = message

            Q_message.save()
            return HttpResponseRedirect('/message/message-list/')
    else:
        return render(request,'msg.html')

def message_list(request):
    objs = Message.objects.all()
    comObjs = Commit.objects.all()
    context = {
        'comObjs': comObjs,
        'objs': objs,
    }
    return render(request, 'message-list.html', context)


def reply(request,id):
    if request.user.is_authenticated:
        uid=id
        relay = 1
        comObjs = Commit.objects.all()
        objs = Message.objects.all()
        context = {
            'comObjs': comObjs,
            'relay':relay,
            'objs': objs,
            'uid':uid,
            }

        return render(request,'message-list.html',context)
    else:
        return HttpResponseRedirect('/userprofile/login')

def commit(request,id):
    if request.method == 'GET':

        cuid=id
        objs = Message.objects.all()
        comObjs = Commit.objects.all()
        print(cuid)
        context = {
            'comObjs':comObjs,
            'cuid': cuid,
            'objs': objs,
        }
        return render(request,'message-list.html',context)
    else:
        st_commit = Commit()
        name=request.user
        text=request.POST.get('text','')
        st_commit.name = name
        st_commit.text = text
        st_commit.mid = id
        st_commit.save()

        return HttpResponseRedirect(
            reverse('message:commit',args=(id,))
        )

Day16/Open-ITBlog/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">

                    <label for="title">文章分类</label>
                    <input type="text" class="form-control"  id="category" name="category">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Day16/Open-ITBlog/templates/article/detail.html
{% extends "base.html" %}
{%load staticfiles %}
{% block title %}
文章详情
{% endblock title%}
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}" rel="stylesheet" type="text/css" />

<!-- 文章详情 -->
<div class="container">
    <div class="row2">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">作者：{{ article.author }}
            {% if user.id == article.author_id %}
           . <a href="#" onclick="confirm_delete()">删除文章</a>
             <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
            {% endif %}
        </div>
        <!-- 文章正文 -->
        <div style="width: 100%;background=#000000;display:block;word-break: break-all;word-wrap: break-word;class="col-12">
            <p>{{ article.body|safe }}</p>
        </div>

    </div>
    <br/>
    <br/>
    <hr class="hr2" />
    <div>
        {% for i in  remark %}
            {% if i.aid == article.id %}
            <p>
         <span class="box4">{{i.name}}</span>
          <p class="box3">{{i.id}}楼 &nbsp; {{i.create_time}} &nbsp;<a href="{% url 'remark:reply' i.id article.id%}"> 回复</a></p>
          <span class="">{{i.text}}</span>
          </p>

            <div class="ncom">
                {% for aReply in articleReply %}
                    {% if aReply.modelsid == i.id %}
                       <span class="box4">{{aReply.name}}</span>：<span class="">{{aReply.text}}</span>
                               <p class="box3">
                                at &nbsp;{{ aReply.create_time }}
                                </p>
                        <HR style="border:1 dashed #987cb9" width="100%" color=#987cb9 SIZE=1>
                    {% endif %}
                {% endfor %}
            </div>
        <br/>
          {% endif %}
         <div class="ncom">
        {% if reply %}
             {% if cid == i.id %}
             <form name="text" method="post" action="{% url 'remark:commit' i.id article.id%}">
                 {% csrf_token %}
                 <input name="text" type="text">
                 <p><button type="submit" class="box3">提交</button></p>
             </form>
             {% endif %}
        <HR style="border:1px dashed #334455" width="80%" color=#987cb9 SIZE=1>
        {% endif %}
        </div>

        {% endfor %}
    </div>

    <div class="row">
        {% if user.is_authenticated %}
            我来评论两句~

        <form method="post" action="{% url 'remark:remark' article.id %}">
            {% csrf_token %}
                    <br/>
            <textarea name="text" style="width: 300px; height: 100px"></textarea>
            <p><button type="submit" class="box3">提交</button></p>
         </form>
        {% else %}
            还没登录？快来
        <a href="{% url 'userprofile:login' %}">登录</a>
        吧！
        {% endif %}
    </div>

</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function(index, layero) {
                // 指定应当前往的 url
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }
</script>
{% endblock content %}

Day16/Open-ITBlog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.1" rel="stylesheet" type="text/css" />
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                      <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span> &nbsp;&nbsp;
                    {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Day16/Open-ITBlog/templates/article/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>评论页面</title>
</head>
<body>
<div align="center">评论页面</div>

<form action="../userprofile" method="post">
    {% for field in Remark %}
    {% csrf_token %}
    <div>
        {{ field.label_tag }}:{{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
<div>
    <input type="submit" value="评论">
</div>
</form>

<hr>
{% for tie in ties %}
<div>
    <ul>
        <li>{{ tie.subject }}</li>
        <li>{{ tie.mail }}</li>
        <li>{{ tie.topic }}</li>
        <li>{{ tie.message }}</li>
        <li>{{ tie.cc_myself }}</li>
    </ul>
    <hr>
</div>
{% endfor %}
</body>
</html>

Day16/Open-ITBlog/templates/article/own.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    我的博客
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.1" rel="stylesheet" type="text/css" />
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                     <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span>
                    {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Day16/Open-ITBlog/templates/article/tag.html
{% extends "base.html" %}
{%load staticfiles %}
{% block title %}
标签
{% endblock title%}
{% block content %}
<link href="{% static 'bootstrap/css/mlist.css' %}?v1.0.0" rel="stylesheet" type="text/css" /><!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <div>
                     <span class="box3" >Time:{{ article.created |date:"Y /m /d"}}</span> &nbsp;&nbsp;
                 {% if article.category%}
                        <a class="post-category post-category-js" href="{% url 'article:searchtag' article.category %}">{{ article.category}}</a>
                    {% endif %}
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

Day16/Open-ITBlog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}